import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Open_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/features/nav/Nav";
import ScrollIndicator from "@/components/layout/ScrollIndicator";
import Footer from "@/features/footer/Footer";
import GlobalProvider from "@/global-utils/context/GlobalProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Powerdeed Technology Resources",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${openSans.variable} antialiased flex flex-col min-h-screen`}
      >
        <SpeedInsights />
        <Nav />
        <ScrollIndicator />
        <GlobalProvider>
          <div className="flex-1">{children}</div>
        </GlobalProvider>
        <Footer />
      </body>
    </html>
  );
}
