import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Open_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/Nav";
import ScrollIndicator from "@/components/layout/ScrollIndicator";
import QuickNavs from "@/components/layout/QuickNavs";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${openSans.variable} antialiased`}
      >
        <Nav />
        <ScrollIndicator />
        <QuickNavs />
        {children}
      </body>
    </html>
  );
}
