import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faBars,
  faXmark,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faBatteryEmpty,
  faBatteryQuarter,
  faBatteryHalf,
  faBatteryThreeQuarters,
  faBatteryFull,
  faChargingStation,
  faSolarPanel,
  faReceipt,
  faQuoteRight,
  faQuoteLeft,
  faCircleArrowRight,
  faCircleArrowLeft,
  faArrowLeft,
  faArrowRight,
  faArrowDown,
  faArrowUp,
  faGem,
  faArrowsToCircle,
  faQuestion,
  faThumbsUp,
  faCrosshairs,
  faChevronLeft,
  faChevronRight,
  faRotate,
} from "@fortawesome/free-solid-svg-icons";

import { faComments, faHardDrive } from "@fortawesome/free-regular-svg-icons";

library.add(
  faBars,
  faXmark,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faBatteryEmpty,
  faBatteryQuarter,
  faBatteryHalf,
  faBatteryThreeQuarters,
  faBatteryFull,
  faChargingStation,
  faSolarPanel,
  faReceipt,
  faComments,
  faHardDrive,
  faQuoteRight,
  faQuoteLeft,
  faCircleArrowRight,
  faCircleArrowLeft,
  faArrowLeft,
  faArrowRight,
  faGem,
  faArrowsToCircle,
  faQuestion,
  faThumbsUp,
  faCrosshairs,
  faChevronLeft,
  faChevronRight,
  faRotate,
  faArrowDown,
  faArrowUp,
);
